version: "3"

networks:
  appservers:

volumes:
  system:
  backup:
  database:

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: mete
    volumes:
    - database:/var/lib/postgresql
    networks:
      appservers:
        aliases:
          - db

  db-backup:
    image: nomaster/postgres-backup
    environment:
      PGPASSWORD: mete
    volumes:
      - backup:/backup
    restart: on-failure
    networks:
      appservers:
    depends_on:
      - db

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: chaosdorf/mete
    environment:
      RAILS_ENV: production
      SENTRY_DSN:
    build: .
    volumes:
      - system:/app/public/system
    restart: on-failure
    networks:
      appservers:
        aliases:
          - app
    depends_on:
      - db

  proxy:
    build:
      context: .
      dockerfile: Dockerfile-proxy
    restart: on-failure
    volumes:
      - system:/usr/share/nginx/html/public/system:ro
    ports:
      - 8081:80
    networks:
      appservers:
    depends_on:
      - backend
